<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Label="Package identity">
    <Authors>Patrick Schop</Authors>
    <Company>PS</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/PatrickSchop/AppPlatform</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <VersionPrefix>0.1.2</VersionPrefix>
  </PropertyGroup>

  <PropertyGroup>
    <VersionSuffix Condition="'$(VersionSuffix)' == '' and '$(GITHUB_ACTIONS)' != 'true'">local</VersionSuffix>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsPackable)' == 'true'">
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>azure-functions;spa;background-tasks;platform</PackageTags>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Condition="$(MSBuildProjectDirectory.Contains('templates\content'))">
    <ExcludeFromSolutionBuild>true</ExcludeFromSolutionBuild>
  </PropertyGroup>

  <!-- NuGet source mapping to allow multiple sources with central package management -->
  <ItemGroup>
    <NuGetSourceMapping Condition="'$(NuGetSourceMapping)' != ''"  Include="NuGetSourceMapping.json" />
  </ItemGroup>
</Project>

