namespace PS.AppPlatform.Data;

/// <summary>
/// Base class for all persisted entities. The Id is generated by the database
/// (NEWID()) and configured automatically by PlatformDbContext.
/// </summary>
public abstract class Entity
{
    public Guid Id { get; set; }
}

