name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: PatrickSchop/AppPlatform/.github/workflows/app-build.yaml@main
    secrets: inherit

  deploy:
    needs: build
    uses: PatrickSchop/AppPlatform/.github/workflows/app-deploy.yaml@main
    secrets: inherit
    with:
      app_name: TINYAPP-NAME
      resource_group: TINYAPP-RESOURCE-GROUP
