<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Wisdi.AppPlatform.Templates</PackageId>
    <PackageType>Template</PackageType>
    <Title>Wisdi tiny app templates</Title>
    <Description>dotnet new templates for Wisdi.AppPlatform.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <NoWarn>$(NoWarn);NU5128;NU5119</NoWarn>
    <EnableDefaultItems>false</EnableDefaultItems>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="content\**\*" Exclude="content\**\bin\**;content\**\obj\**" />
    <Compile Remove="**\*" />
  </ItemGroup>

</Project>
